#!/usr/bin/env bash
# serve_test_feed.sh — Serve a local video file as a looping mock RTSP stream.
#
# Usage:
#   ./test_clips/serve_test_feed.sh <video_file> [port] [stream_name]
#
# Arguments:
#   video_file   Path to the .mp4 (or other ffmpeg-readable) clip to serve.
#   port         RTSP port to listen on.  Default: 8554
#   stream_name  RTSP path component.    Default: test-feeder
#
# The resulting stream will be available at:
#   rtsp://localhost:<port>/<stream_name>
#
# Point your services at that URL instead of the live camera URL while testing.

set -euo pipefail

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------
VIDEO_FILE="${1:-}"
PORT="${2:-8554}"
STREAM_NAME="${3:-test-feeder}"

if [[ -z "$VIDEO_FILE" ]]; then
    echo "Usage: $0 <video_file> [port] [stream_name]" >&2
    echo "" >&2
    echo "Example:" >&2
    echo "  $0 test_clips/feeder_5min.mp4" >&2
    echo "  $0 test_clips/ground_5min.mp4 8555 ground-test" >&2
    exit 1
fi

if [[ ! -f "$VIDEO_FILE" ]]; then
    echo "Error: video file not found: $VIDEO_FILE" >&2
    exit 1
fi

RTSP_URL="rtsp://localhost:${PORT}/${STREAM_NAME}"

# ---------------------------------------------------------------------------
# Check for ffmpeg (always required)
# ---------------------------------------------------------------------------
if ! command -v ffmpeg &>/dev/null; then
    echo "Error: ffmpeg is not installed." >&2
    echo "Install it with:  brew install ffmpeg" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Prefer mediamtx as the RTSP server
# ---------------------------------------------------------------------------
if command -v mediamtx &>/dev/null; then
    echo "mediamtx found — using it as the RTSP server."
    echo ""

    # Write a minimal mediamtx config that listens on the requested port.
    TMPDIR_MTX="$(mktemp -d)"
    CONFIG_FILE="${TMPDIR_MTX}/mediamtx.yml"

    cat > "$CONFIG_FILE" <<EOF
# Minimal mediamtx config generated by serve_test_feed.sh
rtspAddress: :${PORT}
rtmpDisable: true
hlsDisable: true
webrtcDisable: true
paths:
  all:
    source: publisher
EOF

    echo "Starting mediamtx on port ${PORT}..."
    mediamtx "$CONFIG_FILE" &
    MTX_PID=$!

    # Give mediamtx a moment to start before ffmpeg connects.
    sleep 1

    cleanup() {
        echo ""
        echo "Shutting down..."
        kill "$MTX_PID" 2>/dev/null || true
        rm -rf "$TMPDIR_MTX"
    }
    trap cleanup EXIT INT TERM

    echo ""
    echo "Streaming '${VIDEO_FILE}' in a loop."
    echo ""
    echo "  Mock RTSP URL: ${RTSP_URL}"
    echo ""
    echo "Point your services at the URL above instead of the live camera URL."
    echo "Press Ctrl+C to stop."
    echo ""

    # Loop the clip indefinitely into mediamtx.
    ffmpeg -hide_banner -loglevel warning \
        -re -stream_loop -1 -i "$VIDEO_FILE" \
        -c copy -f rtsp "$RTSP_URL"

else
    # ---------------------------------------------------------------------------
    # mediamtx not found — print install instructions
    # ---------------------------------------------------------------------------
    echo "mediamtx is not installed (it is the preferred RTSP server)."
    echo ""
    echo "Install it with:"
    echo "  brew install mediamtx"
    echo ""
    echo "Alternatively, install a release binary from:"
    echo "  https://github.com/bluenviron/mediamtx/releases"
    echo ""
    echo "Once installed, re-run this script:"
    echo "  $0 $VIDEO_FILE $PORT $STREAM_NAME"
    echo ""
    echo "The stream will be available at:"
    echo "  ${RTSP_URL}"
    exit 1
fi
